<?php
/**
 * @file
 * gsa_analytics.module
 * GSA Analytics is intended to implement the General Services Agency's
 * federated (Google) analytics javascript. 
 * https://github.com/GSA/DAP-Gov-wide-GA-Code
 */

/**
 * Implements hook_page_build().
 */
function gsa_analytics_page_build() {
  $path = drupal_get_path('module', 'gsa_analytics');
  drupal_add_js($path .'/js/federated-analytics.all.min.js', array('every_page' => TRUE));
}

/**
 * Implements hook_menu().
 */
function gsa_analytics_menu() {
  $items['admin/config/system/gsa-analytics'] = array(
    'title' => 'GSA Analytics Configuration',
    'description' => 'GSA Analytics Configuration Page',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gsa_analytics_admin_settings_form'),
    'file' => 'gsa_analytics.admin.inc',
    'access callback' => 'user_access',
    'access arguments' => array('access administration pages'),
    'theme callback' => 'variable_get',
    'theme arguments' => array('admin_theme'),
    'type' => MENU_LOCAL_TASK | MENU_NORMAL_ITEM,
    'weight' => 9
  );

  return $items;
}

/**
 * Implements hook_variable_info().
 */
function gsa_analytics_variable_info($options) {
  $variables = array();
  $variables['gsa_analytics_css_selector'] = array(
    'name' => 'gsa_analytics_css_selector',
    'title' => 'CSS selector',
    'type' => 'string',
    'default' => gsa_analytics_css_selector,
    'group' => 'gsa_analytics',
    'module' => 'gsa_analytics',
  );
  return $variables;
}